# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stdmsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stdmsg.proto',
  package='stdmsg',
  syntax='proto2',
  serialized_pb=_b('\n\x0cstdmsg.proto\x12\x06stdmsg\"4\n\x08Position\x12\x0c\n\x01x\x18\x01 \x02(\x01:\x01\x30\x12\x0c\n\x01y\x18\x02 \x02(\x01:\x01\x30\x12\x0c\n\x01z\x18\x03 \x01(\x01:\x01\x30\"?\n\nOrentation\x12\x0f\n\x04roll\x18\x01 \x01(\x01:\x01\x30\x12\x10\n\x05pitch\x18\x02 \x01(\x01:\x01\x30\x12\x0e\n\x03yaw\x18\x03 \x02(\x01:\x01\x30\"R\n\x04Pose\x12\"\n\x08position\x18\x01 \x02(\x0b\x32\x10.stdmsg.Position\x12&\n\norentation\x18\x02 \x02(\x0b\x32\x12.stdmsg.Orentation\"&\n\x08Velocity\x12\x0c\n\x01v\x18\x01 \x02(\x01:\x01\x30\x12\x0c\n\x01w\x18\x02 \x02(\x01:\x01\x30\"\xc7\x02\n\nLaser_Scan\x12/\n\x06\x63onfig\x18\x01 \x02(\x0b\x32\x1f.stdmsg.Laser_Scan.Laser_Config\x12\x0e\n\x06ranges\x18\x02 \x03(\x02\x12\x13\n\x0branges_rssi\x18\n \x03(\x02\x12\x13\n\x0bintensities\x18\x03 \x03(\x02\x12\x1a\n\x04pose\x18\x05 \x02(\x0b\x32\x0c.stdmsg.Pose\x12\x1b\n\x05robot\x18\x06 \x02(\x0b\x32\x0c.stdmsg.Pose\x12\r\n\x05steer\x18\t \x01(\x01\x12\x0e\n\x03seq\x18\x07 \x01(\x05:\x01\x30\x12\x14\n\nannotation\x18\x08 \x01(\t:\x00\x1a`\n\x0cLaser_Config\x12\x11\n\tangle_min\x18\x01 \x02(\x02\x12\x11\n\tangle_max\x18\x02 \x02(\x02\x12\x17\n\x0f\x61ngle_increment\x18\x03 \x02(\x02\x12\x11\n\trange_max\x18\x05 \x02(\x02\"R\n\x0bGlobal_Plan\x12\x1a\n\x04path\x18\x01 \x03(\x0b\x32\x0c.stdmsg.Pose\x12\x0e\n\x03seq\x18\x02 \x01(\x05:\x01\x30\x12\x17\n\x0cgoal_reached\x18\x03 \x01(\x05:\x01\x30\"&\n\x04\x44\x61ta\x12\x0e\n\x04\x64\x61ta\x18\x01 \x01(\x0c:\x00\x12\x0e\n\x03seq\x18\x02 \x01(\x05:\x01\x30\"\'\n\x06String\x12\r\n\x03str\x18\x01 \x01(\t:\x00\x12\x0e\n\x03seq\x18\x02 \x01(\x05:\x01\x30\">\n\tLaserList\x12!\n\x05scans\x18\x01 \x03(\x0b\x32\x12.stdmsg.Laser_Scan\x12\x0e\n\x03seq\x18\x02 \x01(\x05:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='stdmsg.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='stdmsg.Position.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='stdmsg.Position.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='stdmsg.Position.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=76,
)


_ORENTATION = _descriptor.Descriptor(
  name='Orentation',
  full_name='stdmsg.Orentation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll', full_name='stdmsg.Orentation.roll', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='stdmsg.Orentation.pitch', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='stdmsg.Orentation.yaw', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=141,
)


_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='stdmsg.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='stdmsg.Pose.position', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orentation', full_name='stdmsg.Pose.orentation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=225,
)


_VELOCITY = _descriptor.Descriptor(
  name='Velocity',
  full_name='stdmsg.Velocity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v', full_name='stdmsg.Velocity.v', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='stdmsg.Velocity.w', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=265,
)


_LASER_SCAN_LASER_CONFIG = _descriptor.Descriptor(
  name='Laser_Config',
  full_name='stdmsg.Laser_Scan.Laser_Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angle_min', full_name='stdmsg.Laser_Scan.Laser_Config.angle_min', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angle_max', full_name='stdmsg.Laser_Scan.Laser_Config.angle_max', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angle_increment', full_name='stdmsg.Laser_Scan.Laser_Config.angle_increment', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range_max', full_name='stdmsg.Laser_Scan.Laser_Config.range_max', index=3,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=595,
)

_LASER_SCAN = _descriptor.Descriptor(
  name='Laser_Scan',
  full_name='stdmsg.Laser_Scan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='stdmsg.Laser_Scan.config', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ranges', full_name='stdmsg.Laser_Scan.ranges', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ranges_rssi', full_name='stdmsg.Laser_Scan.ranges_rssi', index=2,
      number=10, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intensities', full_name='stdmsg.Laser_Scan.intensities', index=3,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='stdmsg.Laser_Scan.pose', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robot', full_name='stdmsg.Laser_Scan.robot', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='steer', full_name='stdmsg.Laser_Scan.steer', index=6,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='stdmsg.Laser_Scan.seq', index=7,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='annotation', full_name='stdmsg.Laser_Scan.annotation', index=8,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LASER_SCAN_LASER_CONFIG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=595,
)


_GLOBAL_PLAN = _descriptor.Descriptor(
  name='Global_Plan',
  full_name='stdmsg.Global_Plan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='stdmsg.Global_Plan.path', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='stdmsg.Global_Plan.seq', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goal_reached', full_name='stdmsg.Global_Plan.goal_reached', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=679,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='stdmsg.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='stdmsg.Data.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=True, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='stdmsg.Data.seq', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=681,
  serialized_end=719,
)


_STRING = _descriptor.Descriptor(
  name='String',
  full_name='stdmsg.String',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='stdmsg.String.str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='stdmsg.String.seq', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=721,
  serialized_end=760,
)


_LASERLIST = _descriptor.Descriptor(
  name='LaserList',
  full_name='stdmsg.LaserList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scans', full_name='stdmsg.LaserList.scans', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='stdmsg.LaserList.seq', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=762,
  serialized_end=824,
)

_POSE.fields_by_name['position'].message_type = _POSITION
_POSE.fields_by_name['orentation'].message_type = _ORENTATION
_LASER_SCAN_LASER_CONFIG.containing_type = _LASER_SCAN
_LASER_SCAN.fields_by_name['config'].message_type = _LASER_SCAN_LASER_CONFIG
_LASER_SCAN.fields_by_name['pose'].message_type = _POSE
_LASER_SCAN.fields_by_name['robot'].message_type = _POSE
_GLOBAL_PLAN.fields_by_name['path'].message_type = _POSE
_LASERLIST.fields_by_name['scans'].message_type = _LASER_SCAN
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['Orentation'] = _ORENTATION
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['Velocity'] = _VELOCITY
DESCRIPTOR.message_types_by_name['Laser_Scan'] = _LASER_SCAN
DESCRIPTOR.message_types_by_name['Global_Plan'] = _GLOBAL_PLAN
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['String'] = _STRING
DESCRIPTOR.message_types_by_name['LaserList'] = _LASERLIST

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'stdmsg_pb2'
  # @@protoc_insertion_point(class_scope:stdmsg.Position)
  ))
_sym_db.RegisterMessage(Position)

Orentation = _reflection.GeneratedProtocolMessageType('Orentation', (_message.Message,), dict(
  DESCRIPTOR = _ORENTATION,
  __module__ = 'stdmsg_pb2'
  # @@protoc_insertion_point(class_scope:stdmsg.Orentation)
  ))
_sym_db.RegisterMessage(Orentation)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(
  DESCRIPTOR = _POSE,
  __module__ = 'stdmsg_pb2'
  # @@protoc_insertion_point(class_scope:stdmsg.Pose)
  ))
_sym_db.RegisterMessage(Pose)

Velocity = _reflection.GeneratedProtocolMessageType('Velocity', (_message.Message,), dict(
  DESCRIPTOR = _VELOCITY,
  __module__ = 'stdmsg_pb2'
  # @@protoc_insertion_point(class_scope:stdmsg.Velocity)
  ))
_sym_db.RegisterMessage(Velocity)

Laser_Scan = _reflection.GeneratedProtocolMessageType('Laser_Scan', (_message.Message,), dict(

  Laser_Config = _reflection.GeneratedProtocolMessageType('Laser_Config', (_message.Message,), dict(
    DESCRIPTOR = _LASER_SCAN_LASER_CONFIG,
    __module__ = 'stdmsg_pb2'
    # @@protoc_insertion_point(class_scope:stdmsg.Laser_Scan.Laser_Config)
    ))
  ,
  DESCRIPTOR = _LASER_SCAN,
  __module__ = 'stdmsg_pb2'
  # @@protoc_insertion_point(class_scope:stdmsg.Laser_Scan)
  ))
_sym_db.RegisterMessage(Laser_Scan)
_sym_db.RegisterMessage(Laser_Scan.Laser_Config)

Global_Plan = _reflection.GeneratedProtocolMessageType('Global_Plan', (_message.Message,), dict(
  DESCRIPTOR = _GLOBAL_PLAN,
  __module__ = 'stdmsg_pb2'
  # @@protoc_insertion_point(class_scope:stdmsg.Global_Plan)
  ))
_sym_db.RegisterMessage(Global_Plan)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'stdmsg_pb2'
  # @@protoc_insertion_point(class_scope:stdmsg.Data)
  ))
_sym_db.RegisterMessage(Data)

String = _reflection.GeneratedProtocolMessageType('String', (_message.Message,), dict(
  DESCRIPTOR = _STRING,
  __module__ = 'stdmsg_pb2'
  # @@protoc_insertion_point(class_scope:stdmsg.String)
  ))
_sym_db.RegisterMessage(String)

LaserList = _reflection.GeneratedProtocolMessageType('LaserList', (_message.Message,), dict(
  DESCRIPTOR = _LASERLIST,
  __module__ = 'stdmsg_pb2'
  # @@protoc_insertion_point(class_scope:stdmsg.LaserList)
  ))
_sym_db.RegisterMessage(LaserList)


# @@protoc_insertion_point(module_scope)
